[package]
name = "sacrifice"
description = "A feature-rich chess library for Rust"
version = "0.2.0"
edition = "2021"

repository = "https://github.com/fr-therook/sacrifice"
license = "MIT"
keywords = ["chess", "pgn"]

[dependencies]
shakmaty = "0.24"
pgn-reader = "0.23"
