[package]
name = "sacrifice"
description = "A chess library"
version = "0.1.3"
edition = "2021"

repository = "https://github.com/fr-therook/sacrifice"
license = "MIT"
keywords = ["chess", "pgn"]

[dependencies]
shakmaty = "0.23"
pgn-reader = "0.22"

[dependencies.uuid]
version = "1.3.0"
features = ["v4", "fast-rng", "macro-diagnostics"]
